language: go

go:
  - 1.3
  - 1.4
  - 1.7
  - 1.8
  - tip

before_install: go get golang.org/x/tools/cmd/cover
script: go test -race -v -cover ./...

env:
- GOMAXPROCS=8
- GORACE="halt_on_error=1"

notifications:
  email: false
